### ISSUE TITLE
research: support asset baskets?

### ISSUE THREAD

**Issue by z0r0z** [z0r0z/Helios#10]
currently Helios is designed to store a "pair" of assets for a given LP 1155 Id. 

in the wild, there are designed for weighted "baskets" of assets, such as the Balancer LP model for index-style pools.

Two questions:
(a) how common or useful are baskets for AMM users in practice? That is, do most users nonetheless create pairs in Balancer.
(b) how difficult to implement basket array in Helios model?

**Comment by shortdoom** [comment]
I think there is little priority for asset baskets.

a) as noted, most of balancer multiple token pools are basic two token pools or three token pools at max (judging by volume)
b) asset baskets never got any traction in defi, indexes got incredibly rekt too, there is little economical sense for LPs to use those because of overexposure to unwanted assets anyways
c) asset baskets are hard to manage and bare additional protocol/user loss of funds risk

linking to relevant proposition to keep this issue clean: https://github.com/z0r0z/Helios/issues/12

**Comment by z0r0z** [comment]
thank you for your thoughts and research on this matter @shortdoom Let's stick to pair pools.
